### ISSUE TITLE
Importing DB.SQL into CouchDB

### ISSUE THREAD

**Issue by pumpkinpieman** [gbjoel/simplebanking#7]
Hello all,

I'm experiencing some kind of brain fart on how to import the SQL file into the couchDB apache.

Could someone please provide me with some assistance?

**Comment by rudzboy** [comment]
Hum. https://github.com/gbjoel/simplebanking/pull/6
You saw this ?

**Comment by pumpkinpieman** [comment]
Yes.

Apologies. I'll just chop both my hands off now.
